server:
  port: 8081

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://81.94.159.154:3306/nestro
      username: Duke
      password: ZXCursed17
    mvc:
      hiddenmethod:
        filter:
          enabled: true




#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true